# Generated by Django 4.0.6 on 2023-08-03 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='value',
        ),
    ]
